// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 48, boss 4887 (Ghamoo-ra), 24 anchors over 376yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute48_4887()
{
    DungeonClearRouteRegistry::Register(48, DUNGEON_DIFFICULTY_NORMAL, 4887,
        {
            { -151.89f, 106.96f, -39.87f },
            { -148.47f, 89.97f, -41.74f },
            { -156.30f, 81.41f, -44.79f },
            { -167.31f, 66.09f, -45.31f },
            { -172.04f, 59.17f, -47.63f },
            { -191.28f, 51.94f, -51.91f },
            { -210.18f, 44.19f, -52.68f },
            { -227.80f, 37.90f, -53.95f },
            { -249.46f, 33.37f, -55.29f },
            { -249.28f, 41.59f, -55.09f },
            { -260.70f, 52.77f, -55.30f },
            { -276.92f, 60.30f, -62.13f },
            { -288.78f, 59.73f, -65.88f },
            { -305.78f, 67.26f, -64.07f },
            { -322.20f, 71.14f, -62.28f },
            { -324.50f, 90.53f, -58.92f },
            { -322.90f, 106.59f, -55.31f },
            { -326.40f, 114.33f, -50.96f },
            { -339.14f, 125.09f, -49.94f },
            { -354.28f, 140.49f, -49.61f },
            { -370.19f, 155.38f, -52.62f },
            { -380.83f, 168.40f, -56.26f },
            { -398.05f, 178.10f, -56.42f },
            { -404.93f, 183.06f, -56.05f },
        });
}
