// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 1763 (Gilnid), 17 anchors over 204yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_1763()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 1763,
        {
            { -290.23f, -521.43f, 49.60f },
            { -293.46f, -529.15f, 49.26f },
            { -287.97f, -547.24f, 49.38f },
            { -285.12f, -554.91f, 49.44f },
            { -288.17f, -565.83f, 49.70f },
            { -302.44f, -576.58f, 49.41f },
            { -298.95f, -588.26f, 47.51f },
            { -290.53f, -592.57f, 49.17f },
            { -272.18f, -583.50f, 50.93f },
            { -261.48f, -581.28f, 44.98f },
            { -251.92f, -578.71f, 32.69f },
            { -242.02f, -576.04f, 19.95f },
            { -236.43f, -570.17f, 19.72f },
            { -225.52f, -581.95f, 21.16f },
            { -221.23f, -589.08f, 21.89f },
            { -212.18f, -570.46f, 21.59f },
            { -198.74f, -573.29f, 21.14f },
        });
}
