// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 129, boss 7358 (Amnennar the Coldbringer), 53 anchors over 808yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute129_7358()
{
    DungeonClearRouteRegistry::Register(129, DUNGEON_DIFFICULTY_NORMAL, 7358,
        {
            { 2592.55f, 1107.50f, 51.29f },
            { 2586.78f, 1088.90f, 52.57f },
            { 2578.91f, 1074.37f, 54.89f },
            { 2565.88f, 1057.52f, 53.42f },
            { 2547.53f, 1048.29f, 48.32f },
            { 2529.66f, 1048.14f, 46.88f },
            { 2513.23f, 1051.64f, 47.37f },
            { 2497.13f, 1059.13f, 47.39f },
            { 2477.67f, 1065.67f, 47.62f },
            { 2460.74f, 1071.70f, 47.56f },
            { 2445.78f, 1079.04f, 42.87f },
            { 2429.18f, 1084.92f, 36.84f },
            { 2419.23f, 1087.25f, 33.07f },
            { 2409.84f, 1090.08f, 31.71f },
            { 2397.15f, 1077.04f, 30.12f },
            { 2388.98f, 1061.54f, 26.26f },
            { 2380.46f, 1043.25f, 24.68f },
            { 2401.81f, 1042.61f, 25.28f },
            { 2418.57f, 1042.21f, 25.14f },
            { 2433.09f, 1036.75f, 25.08f },
            { 2449.56f, 1026.56f, 25.35f },
            { 2456.38f, 1019.27f, 25.17f },
            { 2462.70f, 1001.34f, 24.93f },
            { 2468.37f, 986.04f, 24.30f },
            { 2470.18f, 968.30f, 25.39f },
            { 2469.40f, 952.02f, 24.89f },
            { 2466.24f, 944.55f, 25.45f },
            { 2463.57f, 944.71f, 32.25f },
            { 2466.81f, 960.75f, 36.46f },
            { 2450.20f, 978.88f, 36.39f },
            { 2447.38f, 995.65f, 37.19f },
            { 2438.77f, 1010.81f, 38.05f },
            { 2431.46f, 1015.55f, 37.82f },
            { 2414.69f, 1018.97f, 37.48f },
            { 2413.26f, 1011.03f, 37.69f },
            { 2393.63f, 1009.16f, 38.57f },
            { 2376.17f, 1007.62f, 39.38f },
            { 2368.46f, 1005.05f, 38.32f },
            { 2362.84f, 995.18f, 39.81f },
            { 2368.97f, 975.08f, 41.13f },
            { 2368.39f, 966.94f, 44.39f },
            { 2367.29f, 949.18f, 41.61f },
            { 2370.83f, 941.62f, 42.12f },
            { 2392.61f, 937.27f, 43.36f },
            { 2408.85f, 939.21f, 46.82f },
            { 2418.81f, 944.09f, 45.61f },
            { 2426.01f, 958.67f, 45.62f },
            { 2426.38f, 978.05f, 48.43f },
            { 2424.32f, 987.16f, 48.98f },
            { 2403.16f, 992.05f, 51.70f },
            { 2395.30f, 989.36f, 53.04f },
            { 2398.97f, 982.05f, 56.11f },
            { 2402.16f, 970.27f, 55.49f },
        });
}
