// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3669 (Lord Cobrahn), 39 anchors over 616yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3669()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3669,
        {
            { -38.03f, 295.93f, -106.37f },
            { -50.51f, 306.98f, -106.30f },
            { -66.74f, 322.08f, -106.48f },
            { -71.29f, 341.61f, -105.66f },
            { -65.32f, 362.79f, -106.31f },
            { -62.19f, 377.92f, -104.82f },
            { -59.35f, 394.97f, -105.57f },
            { -59.70f, 412.94f, -106.32f },
            { -45.40f, 431.65f, -105.14f },
            { -31.52f, 446.90f, -102.11f },
            { -19.73f, 458.85f, -97.58f },
            { -4.71f, 464.96f, -90.57f },
            { 2.85f, 461.33f, -84.05f },
            { 5.81f, 457.82f, -78.52f },
            { 1.03f, 440.28f, -72.39f },
            { -1.80f, 425.50f, -67.68f },
            { -2.97f, 414.79f, -65.85f },
            { 3.48f, 406.68f, -60.61f },
            { 19.80f, 399.60f, -59.63f },
            { 40.49f, 399.36f, -60.37f },
            { 50.36f, 412.25f, -63.50f },
            { 55.96f, 429.96f, -64.22f },
            { 63.07f, 434.52f, -64.33f },
            { 50.53f, 450.12f, -65.49f },
            { 43.11f, 466.01f, -65.94f },
            { 30.27f, 480.51f, -65.67f },
            { 18.20f, 491.71f, -61.22f },
            { 7.61f, 493.79f, -58.15f },
            { -11.96f, 494.45f, -55.86f },
            { -26.42f, 479.46f, -54.51f },
            { -43.16f, 478.14f, -55.60f },
            { -62.93f, 474.33f, -60.80f },
            { -71.54f, 471.55f, -64.09f },
            { -79.43f, 467.59f, -67.12f },
            { -97.65f, 451.34f, -71.48f },
            { -107.65f, 437.63f, -72.97f },
            { -118.03f, 420.83f, -72.81f },
            { -123.29f, 413.73f, -72.16f },
            { -132.11f, 412.54f, -72.72f },
        });
}
