// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 48, boss 62530 (Velthelaxx the Defiler), 37 anchors over 584yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute48_62530()
{
    DungeonClearRouteRegistry::Register(48, DUNGEON_DIFFICULTY_NORMAL, 62530,
        {
            { -439.20f, 21.31f, -47.57f },
            { -454.37f, 11.82f, -47.97f },
            { -470.18f, 4.40f, -47.75f },
            { -485.44f, -3.01f, -46.99f },
            { -500.70f, -11.10f, -45.47f },
            { -515.65f, -25.07f, -42.67f },
            { -530.24f, -38.32f, -38.81f },
            { -546.37f, -42.37f, -39.01f },
            { -567.74f, -38.50f, -35.29f },
            { -576.72f, -41.62f, -33.79f },
            { -593.53f, -40.62f, -29.52f },
            { -615.49f, -33.06f, -23.63f },
            { -633.67f, -26.63f, -19.40f },
            { -649.62f, -21.56f, -17.75f },
            { -660.09f, -8.93f, -19.53f },
            { -669.59f, 5.15f, -23.65f },
            { -684.51f, 18.56f, -28.53f },
            { -699.19f, 25.79f, -29.13f },
            { -707.13f, 28.36f, -29.28f },
            { -714.85f, 25.47f, -29.56f },
            { -721.00f, 15.97f, -29.84f },
            { -721.05f, -0.78f, -32.64f },
            { -720.06f, -12.36f, -36.62f },
            { -719.17f, -20.46f, -37.65f },
            { -713.33f, -26.74f, -35.86f },
            { -702.54f, -27.04f, -32.67f },
            { -685.86f, -31.12f, -29.98f },
            { -665.75f, -36.18f, -30.12f },
            { -656.61f, -54.58f, -28.23f },
            { -650.59f, -72.41f, -29.26f },
            { -634.86f, -79.87f, -29.39f },
            { -629.40f, -99.12f, -27.83f },
            { -626.74f, -117.62f, -29.20f },
            { -623.19f, -134.10f, -28.24f },
            { -619.17f, -154.88f, -28.24f },
            { -617.29f, -171.63f, -28.32f },
            { -615.16f, -179.94f, -28.83f },
        });
}
