// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 47, boss 6168 (Roogug), 23 anchors over 345yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute47_6168()
{
    DungeonClearRouteRegistry::Register(47, DUNGEON_DIFFICULTY_NORMAL, 6168,
        {
            { 1943.00f, 1544.63f, 82.00f },
            { 1947.33f, 1560.70f, 82.18f },
            { 1951.66f, 1568.42f, 83.23f },
            { 1955.17f, 1587.01f, 81.85f },
            { 1969.58f, 1597.20f, 81.40f },
            { 1985.36f, 1601.53f, 79.75f },
            { 1991.52f, 1607.01f, 80.72f },
            { 2000.43f, 1626.03f, 81.46f },
            { 2009.89f, 1644.30f, 80.33f },
            { 2024.99f, 1654.29f, 82.13f },
            { 2042.51f, 1649.35f, 82.60f },
            { 2047.87f, 1643.26f, 83.86f },
            { 2050.69f, 1626.39f, 81.98f },
            { 2051.33f, 1618.02f, 81.02f },
            { 2063.66f, 1601.73f, 76.75f },
            { 2072.83f, 1587.34f, 80.12f },
            { 2083.76f, 1570.66f, 82.42f },
            { 2094.90f, 1557.99f, 81.46f },
            { 2100.70f, 1552.02f, 81.60f },
            { 2116.47f, 1560.94f, 81.32f },
            { 2115.42f, 1581.11f, 82.08f },
            { 2132.70f, 1581.60f, 81.33f },
            { 2142.01f, 1581.30f, 81.23f },
        });
}
