// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 33, boss 3927 (Wolf Master Nandos), 18 anchors over 283yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute33_3927()
{
    DungeonClearRouteRegistry::Register(33, DUNGEON_DIFFICULTY_NORMAL, 3927,
        {
            { -154.16f, 2177.14f, 128.86f },
            { -133.90f, 2168.89f, 128.74f },
            { -125.64f, 2167.10f, 129.00f },
            { -120.44f, 2175.06f, 130.35f },
            { -124.35f, 2190.89f, 132.45f },
            { -139.42f, 2200.67f, 134.74f },
            { -156.46f, 2199.22f, 136.94f },
            { -167.00f, 2188.00f, 138.69f },
            { -160.41f, 2171.39f, 138.70f },
            { -156.28f, 2163.54f, 138.70f },
            { -139.69f, 2160.97f, 138.70f },
            { -120.01f, 2175.37f, 140.42f },
            { -127.33f, 2194.31f, 144.13f },
            { -143.26f, 2201.06f, 147.37f },
            { -154.60f, 2199.95f, 149.47f },
            { -167.20f, 2187.11f, 151.90f },
            { -138.11f, 2170.59f, 155.68f },
            { -145.42f, 2174.10f, 156.23f },
        });
}
