// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 389, boss 11518 (Jergosh the Invoker), 45 anchors over 774yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute389_11518()
{
    DungeonClearRouteRegistry::Register(389, DUNGEON_DIFFICULTY_NORMAL, 11518,
        {
            { -244.74f, 150.09f, -18.75f },
            { -221.29f, 152.50f, -19.46f },
            { -200.91f, 148.90f, -25.03f },
            { -197.14f, 130.90f, -22.95f },
            { -200.79f, 149.05f, -25.55f },
            { -221.35f, 154.84f, -19.61f },
            { -233.33f, 158.77f, -28.33f },
            { -238.67f, 170.01f, -18.60f },
            { -242.15f, 152.86f, -18.73f },
            { -246.98f, 129.09f, -18.70f },
            { -262.83f, 113.97f, -24.54f },
            { -268.07f, 108.78f, -25.01f },
            { -267.76f, 103.57f, -24.46f },
            { -258.82f, 108.76f, -23.83f },
            { -249.18f, 135.80f, -18.47f },
            { -260.69f, 147.33f, -18.66f },
            { -286.47f, 155.19f, -25.42f },
            { -297.74f, 154.07f, -24.40f },
            { -284.62f, 153.49f, -24.82f },
            { -292.99f, 160.87f, -24.57f },
            { -295.24f, 173.34f, -20.43f },
            { -292.43f, 160.33f, -25.10f },
            { -273.39f, 152.84f, -21.32f },
            { -251.40f, 154.32f, -18.78f },
            { -232.98f, 155.64f, -30.15f },
            { -215.61f, 156.88f, -20.76f },
            { -193.38f, 160.16f, -25.22f },
            { -181.05f, 163.27f, -25.13f },
            { -185.99f, 195.93f, -25.62f },
            { -202.56f, 210.03f, -23.62f },
            { -231.42f, 212.46f, -24.38f },
            { -226.70f, 212.21f, -24.95f },
            { -240.34f, 209.78f, -24.99f },
            { -239.95f, 200.12f, -24.45f },
            { -241.14f, 205.93f, -24.05f },
            { -253.85f, 208.13f, -20.80f },
            { -237.56f, 196.65f, -24.69f },
            { -247.11f, 213.40f, -23.02f },
            { -275.82f, 219.82f, -25.02f },
            { -296.67f, 201.89f, -24.81f },
            { -295.65f, 214.67f, -25.44f },
            { -315.31f, 222.39f, -21.88f },
            { -314.96f, 215.04f, -21.78f },
            { -334.35f, 210.07f, -20.69f },
            { -359.65f, 211.47f, -21.19f },
        });
}
