// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 90, boss 7800 (Mekgineer Thermaplugg), 10 anchors over 130yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute90_7800()
{
    DungeonClearRouteRegistry::Register(90, DUNGEON_DIFFICULTY_NORMAL, 7800,
        {
            { -539.39f, 527.26f, -215.51f },
            { -545.57f, 534.96f, -216.70f },
            { -543.26f, 553.43f, -219.74f },
            { -539.75f, 571.17f, -224.93f },
            { -538.84f, 579.74f, -228.10f },
            { -538.86f, 584.53f, -325.26f },
            { -540.98f, 600.85f, -325.69f },
            { -544.66f, 617.81f, -326.74f },
            { -549.36f, 637.09f, -326.76f },
            { -561.25f, 648.77f, -326.71f },
        });
}
