// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 34, boss 1666 (Kam Deepfury), 7 anchors over 93yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute34_1666()
{
    DungeonClearRouteRegistry::Register(34, DUNGEON_DIFFICULTY_NORMAL, 1666,
        {
            { 159.58f, 1.25f, -25.61f },
            { 140.98f, -0.14f, -25.61f },
            { 131.69f, -4.60f, -25.61f },
            { 129.74f, -23.39f, -30.48f },
            { 128.89f, -41.94f, -33.94f },
            { 127.43f, -59.64f, -33.94f },
            { 132.28f, -68.18f, -34.78f },
        });
}
