// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 47, boss 4422 (Agathelos the Raging), 47 anchors over 685yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute47_4422()
{
    DungeonClearRouteRegistry::Register(47, DUNGEON_DIFFICULTY_NORMAL, 4422,
        {
            { 1982.30f, 1827.97f, 83.89f },
            { 1996.15f, 1817.97f, 80.70f },
            { 1993.21f, 1807.34f, 78.27f },
            { 1987.48f, 1801.69f, 76.90f },
            { 1970.75f, 1798.23f, 72.75f },
            { 1964.65f, 1792.10f, 70.92f },
            { 1963.30f, 1783.76f, 70.28f },
            { 1966.26f, 1776.31f, 70.12f },
            { 1972.44f, 1770.58f, 68.03f },
            { 1980.47f, 1768.97f, 64.36f },
            { 1983.76f, 1776.56f, 59.84f },
            { 1978.79f, 1786.95f, 54.58f },
            { 1979.95f, 1804.21f, 50.15f },
            { 1988.97f, 1806.55f, 50.68f },
            { 1989.98f, 1788.71f, 52.28f },
            { 1989.73f, 1770.39f, 55.21f },
            { 1988.51f, 1753.63f, 58.14f },
            { 1988.29f, 1734.37f, 60.10f },
            { 1984.35f, 1718.25f, 59.51f },
            { 1985.89f, 1700.64f, 59.50f },
            { 1993.82f, 1685.93f, 62.68f },
            { 2006.12f, 1682.29f, 66.12f },
            { 2013.89f, 1685.33f, 67.08f },
            { 2025.94f, 1699.16f, 70.21f },
            { 2038.30f, 1711.70f, 73.16f },
            { 2055.94f, 1724.33f, 76.77f },
            { 2065.58f, 1739.26f, 76.54f },
            { 2075.13f, 1754.00f, 77.32f },
            { 2084.96f, 1767.89f, 78.70f },
            { 2095.31f, 1787.73f, 75.19f },
            { 2102.40f, 1807.02f, 75.19f },
            { 2105.52f, 1815.26f, 78.30f },
            { 2110.21f, 1831.10f, 79.43f },
            { 2110.50f, 1840.89f, 76.38f },
            { 2111.05f, 1859.32f, 73.32f },
            { 2115.92f, 1880.38f, 71.94f },
            { 2106.99f, 1900.92f, 71.03f },
            { 2093.88f, 1912.78f, 68.95f },
            { 2087.73f, 1932.27f, 65.93f },
            { 2087.84f, 1941.70f, 64.74f },
            { 2071.87f, 1943.59f, 63.80f },
            { 2065.79f, 1952.66f, 61.58f },
            { 2067.04f, 1969.95f, 62.28f },
            { 2065.73f, 1988.35f, 63.67f },
            { 2062.15f, 2008.35f, 64.00f },
            { 2055.34f, 2015.48f, 62.59f },
            { 2046.89f, 2015.70f, 60.03f },
        });
}
