// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 48, boss 4832 (Twilight Lord Kelris), 33 anchors over 447yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute48_4832()
{
    DungeonClearRouteRegistry::Register(48, DUNGEON_DIFFICULTY_NORMAL, 4832,
        {
            { -625.96f, -197.67f, -25.03f },
            { -617.22f, -196.45f, -25.55f },
            { -614.52f, -177.94f, -28.34f },
            { -618.60f, -161.68f, -28.24f },
            { -623.93f, -141.96f, -29.36f },
            { -626.44f, -120.80f, -29.15f },
            { -628.20f, -104.04f, -28.35f },
            { -629.51f, -86.80f, -29.38f },
            { -643.47f, -72.98f, -28.85f },
            { -651.40f, -68.34f, -29.07f },
            { -658.70f, -48.92f, -29.77f },
            { -662.67f, -39.81f, -30.01f },
            { -680.88f, -31.67f, -30.14f },
            { -699.74f, -32.32f, -30.91f },
            { -708.31f, -32.35f, -34.75f },
            { -716.63f, -36.25f, -37.34f },
            { -723.73f, -51.44f, -37.37f },
            { -730.46f, -58.46f, -35.35f },
            { -750.84f, -60.96f, -32.94f },
            { -759.84f, -60.49f, -32.04f },
            { -776.19f, -67.11f, -29.91f },
            { -784.26f, -63.87f, -33.69f },
            { -801.29f, -61.84f, -31.07f },
            { -809.70f, -62.39f, -29.70f },
            { -814.60f, -68.76f, -29.71f },
            { -816.05f, -85.18f, -27.98f },
            { -815.29f, -89.14f, -33.77f },
            { -815.08f, -98.51f, -25.73f },
            { -820.61f, -105.47f, -25.86f },
            { -828.22f, -108.86f, -25.87f },
            { -833.05f, -115.49f, -25.87f },
            { -827.32f, -132.69f, -25.87f },
            { -819.98f, -153.38f, -25.89f },
        });
}
