// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 5775 (Verdan the Everliving), 3 anchors over 40yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_5775()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 5775,
        {
            { -104.23f, -10.19f, -28.19f },
            { -94.40f, 9.97f, -30.74f },
            { -84.25f, 24.52f, -31.08f },
        });
}
