// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 5712 (Zolo), 45 anchors over 583yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_5712()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 5712,
        {
            { -319.24f, 99.90f, -131.85f },
            { -339.01f, 109.31f, -131.85f },
            { -357.18f, 117.18f, -131.85f },
            { -368.96f, 129.27f, -131.86f },
            { -383.06f, 139.88f, -131.71f },
            { -388.86f, 146.03f, -131.86f },
            { -390.10f, 154.51f, -130.93f },
            { -381.19f, 171.27f, -128.90f },
            { -373.16f, 168.43f, -122.90f },
            { -365.52f, 165.15f, -117.08f },
            { -357.18f, 161.57f, -110.74f },
            { -349.74f, 157.76f, -109.07f },
            { -355.47f, 151.95f, -106.96f },
            { -362.93f, 154.91f, -101.22f },
            { -372.46f, 158.68f, -93.98f },
            { -378.03f, 160.89f, -89.88f },
            { -384.23f, 166.76f, -89.24f },
            { -373.56f, 169.24f, -84.18f },
            { -365.32f, 165.53f, -77.63f },
            { -356.89f, 161.73f, -70.94f },
            { -342.31f, 149.76f, -68.93f },
            { -343.37f, 131.36f, -67.41f },
            { -349.34f, 125.25f, -61.68f },
            { -355.78f, 118.66f, -55.48f },
            { -364.53f, 112.96f, -53.98f },
            { -378.47f, 130.09f, -53.72f },
            { -389.28f, 144.44f, -53.95f },
            { -400.80f, 155.92f, -53.95f },
            { -407.10f, 161.33f, -53.95f },
            { -417.46f, 162.84f, -53.95f },
            { -419.71f, 173.72f, -53.95f },
            { -437.44f, 184.29f, -53.95f },
            { -445.38f, 182.19f, -53.95f },
            { -462.92f, 186.11f, -53.95f },
            { -479.49f, 185.60f, -53.95f },
            { -501.85f, 182.28f, -53.95f },
            { -518.87f, 179.40f, -54.10f },
            { -535.66f, 178.99f, -54.01f },
            { -553.27f, 181.38f, -63.02f },
            { -560.26f, 185.55f, -67.63f },
            { -569.10f, 175.82f, -69.40f },
            { -562.28f, 166.62f, -69.40f },
            { -546.23f, 162.89f, -69.40f },
            { -532.55f, 150.13f, -68.38f },
            { -530.39f, 140.80f, -65.76f },
        });
}
