// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 429, boss 11490 (Zevrim Thornhoof), 27 anchors over 397yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute429_11490()
{
    DungeonClearRouteRegistry::Register(429, DUNGEON_DIFFICULTY_NORMAL, 11490,
        {
            { -46.78f, -446.85f, -57.77f },
            { -35.65f, -446.78f, -58.62f },
            { -29.54f, -428.63f, -61.04f },
            { -27.28f, -420.04f, -59.95f },
            { -21.36f, -446.18f, -58.08f },
            { -0.39f, -446.59f, -58.63f },
            { 17.13f, -448.42f, -58.63f },
            { 34.71f, -448.89f, -58.62f },
            { 53.36f, -448.42f, -58.60f },
            { 61.43f, -450.19f, -58.59f },
            { 68.01f, -443.00f, -58.60f },
            { 69.29f, -434.75f, -58.60f },
            { 83.97f, -446.98f, -57.80f },
            { 98.96f, -453.11f, -55.42f },
            { 105.83f, -457.28f, -54.13f },
            { 111.89f, -472.77f, -50.92f },
            { 104.59f, -486.97f, -47.67f },
            { 88.78f, -492.00f, -44.33f },
            { 72.50f, -492.33f, -42.12f },
            { 53.50f, -492.15f, -39.53f },
            { 37.08f, -492.57f, -37.66f },
            { 19.70f, -492.58f, -36.41f },
            { 3.58f, -490.36f, -36.41f },
            { -1.57f, -484.07f, -36.41f },
            { -3.95f, -472.95f, -36.56f },
            { -16.57f, -460.71f, -37.96f },
            { -25.98f, -448.24f, -36.09f },
        });
}
