// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 61965 (Vangros), 39 anchors over 664yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_61965()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 61965,
        {
            { -269.30f, -299.57f, -67.74f },
            { -264.05f, -279.14f, -65.69f },
            { -266.68f, -262.42f, -64.19f },
            { -272.14f, -246.41f, -61.52f },
            { -274.14f, -228.02f, -62.90f },
            { -276.99f, -211.26f, -63.22f },
            { -279.39f, -193.59f, -62.38f },
            { -291.22f, -179.79f, -61.49f },
            { -303.02f, -168.37f, -60.77f },
            { -310.67f, -153.05f, -60.68f },
            { -309.21f, -143.15f, -61.88f },
            { -325.28f, -134.43f, -61.99f },
            { -338.05f, -122.99f, -63.08f },
            { -352.06f, -114.08f, -64.06f },
            { -369.27f, -103.89f, -64.82f },
            { -378.65f, -88.23f, -65.56f },
            { -386.93f, -72.64f, -65.30f },
            { -397.01f, -55.70f, -65.22f },
            { -404.45f, -38.79f, -65.26f },
            { -410.11f, -23.38f, -65.16f },
            { -423.74f, -9.35f, -65.36f },
            { -440.05f, -6.84f, -64.71f },
            { -458.79f, -8.23f, -65.37f },
            { -476.83f, -14.85f, -67.17f },
            { -491.39f, -23.03f, -67.82f },
            { -498.25f, -41.46f, -67.67f },
            { -508.13f, -61.04f, -67.17f },
            { -512.89f, -77.41f, -67.62f },
            { -516.60f, -93.64f, -67.36f },
            { -517.76f, -110.48f, -68.63f },
            { -518.73f, -128.34f, -69.23f },
            { -502.45f, -137.31f, -66.21f },
            { -493.49f, -151.81f, -66.06f },
            { -480.95f, -162.09f, -64.94f },
            { -468.57f, -173.83f, -65.05f },
            { -458.07f, -188.88f, -64.91f },
            { -443.58f, -197.06f, -65.00f },
            { -430.83f, -208.20f, -67.27f },
            { -423.20f, -214.87f, -65.90f },
        });
}
