// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 33, boss 3914 (Rethilgore), 6 anchors over 95yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute33_3914()
{
    DungeonClearRouteRegistry::Register(33, DUNGEON_DIFFICULTY_NORMAL, 3914,
        {
            { -229.13f, 2109.18f, 76.89f },
            { -195.79f, 2130.52f, 81.90f },
            { -195.27f, 2140.32f, 85.45f },
            { -203.29f, 2142.70f, 88.88f },
            { -220.90f, 2142.97f, 90.67f },
            { -241.29f, 2141.70f, 87.33f },
        });
}
