// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 48, boss 4830 (Old Serra'kis), 30 anchors over 445yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute48_4830()
{
    DungeonClearRouteRegistry::Register(48, DUNGEON_DIFFICULTY_NORMAL, 4830,
        {
            { -832.50f, -249.03f, -25.59f },
            { -827.72f, -231.89f, -25.34f },
            { -822.45f, -212.95f, -25.34f },
            { -817.59f, -195.53f, -25.34f },
            { -813.10f, -179.41f, -25.30f },
            { -809.75f, -161.01f, -25.34f },
            { -807.94f, -143.94f, -25.27f },
            { -804.32f, -124.00f, -25.30f },
            { -803.44f, -115.67f, -25.33f },
            { -808.42f, -108.68f, -25.32f },
            { -816.17f, -104.90f, -25.34f },
            { -813.86f, -83.32f, -26.57f },
            { -812.29f, -63.80f, -29.14f },
            { -793.46f, -62.14f, -29.14f },
            { -772.65f, -66.40f, -28.97f },
            { -756.37f, -60.60f, -29.34f },
            { -737.82f, -62.80f, -29.44f },
            { -729.07f, -63.32f, -29.44f },
            { -725.67f, -81.52f, -29.44f },
            { -726.11f, -99.23f, -29.45f },
            { -744.72f, -107.96f, -32.17f },
            { -753.49f, -110.82f, -37.40f },
            { -770.77f, -105.99f, -38.07f },
            { -786.92f, -102.40f, -36.38f },
            { -795.73f, -98.75f, -37.58f },
            { -796.05f, -107.04f, -37.67f },
            { -791.01f, -114.35f, -35.66f },
            { -796.66f, -124.52f, -35.75f },
            { -793.74f, -140.74f, -38.56f },
            { -788.94f, -149.15f, -42.09f },
        });
}
