// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 33, boss 4275 (Archmage Arugal), 7 anchors over 70yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute33_4275()
{
    DungeonClearRouteRegistry::Register(33, DUNGEON_DIFFICULTY_NORMAL, 4275,
        {
            { -128.29f, 2161.21f, 156.21f },
            { -117.64f, 2157.35f, 155.11f },
            { -112.97f, 2150.15f, 152.70f },
            { -113.42f, 2141.86f, 146.99f },
            { -94.17f, 2139.29f, 145.10f },
            { -80.77f, 2144.49f, 150.86f },
            { -76.82f, 2152.27f, 155.71f },
        });
}
