// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 189, boss 6487 (Arcanist Doan), 31 anchors over 461yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute189_6487()
{
    DungeonClearRouteRegistry::Register(189, DUNGEON_DIFFICULTY_NORMAL, 6487,
        {
            { 255.35f, -209.09f, 18.68f },
            { 263.80f, -209.87f, 19.20f },
            { 267.02f, -219.47f, 19.10f },
            { 248.04f, -229.73f, 19.12f },
            { 230.38f, -228.58f, 19.34f },
            { 222.15f, -226.88f, 19.13f },
            { 205.91f, -233.04f, 18.61f },
            { 197.90f, -249.01f, 19.20f },
            { 187.65f, -267.07f, 18.55f },
            { 177.44f, -280.63f, 18.88f },
            { 175.66f, -301.88f, 18.99f },
            { 174.89f, -310.26f, 18.53f },
            { 192.02f, -310.05f, 18.53f },
            { 210.42f, -309.61f, 18.53f },
            { 218.48f, -311.84f, 18.53f },
            { 230.15f, -325.94f, 19.12f },
            { 248.07f, -330.07f, 19.11f },
            { 262.51f, -338.45f, 18.82f },
            { 264.65f, -354.97f, 20.08f },
            { 269.61f, -370.71f, 20.08f },
            { 262.31f, -385.15f, 20.65f },
            { 257.89f, -392.53f, 21.08f },
            { 257.71f, -400.82f, 20.41f },
            { 265.89f, -415.58f, 20.53f },
            { 257.39f, -424.02f, 18.53f },
            { 241.01f, -426.20f, 18.53f },
            { 222.94f, -421.87f, 19.56f },
            { 213.72f, -428.26f, 18.53f },
            { 197.11f, -428.71f, 18.53f },
            { 176.68f, -428.87f, 18.53f },
            { 160.69f, -425.27f, 18.50f },
        });
}
