// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 189, boss 3975 (Herod), 34 anchors over 489yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute189_3975()
{
    DungeonClearRouteRegistry::Register(189, DUNGEON_DIFFICULTY_NORMAL, 3975,
        {
            { 1610.83f, -323.43f, 18.67f },
            { 1627.44f, -332.97f, 18.01f },
            { 1635.04f, -340.43f, 18.68f },
            { 1656.58f, -339.40f, 18.68f },
            { 1664.82f, -340.73f, 19.27f },
            { 1677.45f, -352.03f, 18.02f },
            { 1696.01f, -359.19f, 18.03f },
            { 1712.80f, -363.44f, 18.68f },
            { 1729.46f, -364.94f, 12.50f },
            { 1739.61f, -365.27f, 8.31f },
            { 1747.48f, -368.53f, 8.01f },
            { 1763.14f, -382.50f, 8.21f },
            { 1776.03f, -394.47f, 8.01f },
            { 1781.36f, -400.70f, 8.01f },
            { 1791.24f, -404.03f, 8.01f },
            { 1803.27f, -416.73f, 8.01f },
            { 1809.12f, -424.45f, 8.01f },
            { 1829.18f, -426.36f, 14.65f },
            { 1846.00f, -422.73f, 18.68f },
            { 1854.72f, -404.77f, 18.68f },
            { 1853.52f, -395.36f, 18.68f },
            { 1859.74f, -389.33f, 19.09f },
            { 1869.24f, -390.70f, 19.26f },
            { 1884.43f, -402.64f, 18.68f },
            { 1892.51f, -402.40f, 18.68f },
            { 1901.00f, -386.13f, 18.68f },
            { 1900.16f, -378.06f, 19.26f },
            { 1912.58f, -364.61f, 18.68f },
            { 1921.16f, -364.00f, 18.32f },
            { 1925.28f, -387.28f, 18.01f },
            { 1927.87f, -407.93f, 18.01f },
            { 1930.57f, -426.14f, 18.01f },
            { 1940.25f, -428.77f, 17.17f },
            { 1953.94f, -417.75f, 13.90f },
        });
}
