// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 644 (Rhahk'Zor), 14 anchors over 197yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_644()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 644,
        {
            { -16.40f, -383.07f, 61.78f },
            { -36.22f, -374.77f, 58.58f },
            { -44.17f, -371.51f, 57.32f },
            { -62.56f, -375.56f, 54.83f },
            { -85.59f, -377.40f, 56.99f },
            { -94.73f, -378.47f, 58.94f },
            { -105.51f, -391.65f, 57.96f },
            { -111.37f, -401.78f, 58.89f },
            { -117.09f, -395.92f, 57.57f },
            { -125.58f, -397.33f, 58.62f },
            { -141.69f, -407.73f, 58.20f },
            { -158.27f, -405.41f, 58.22f },
            { -175.17f, -408.11f, 56.03f },
            { -183.33f, -423.36f, 54.60f },
        });
}
