// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3674 (Skum), 20 anchors over 321yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3674()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3674,
        {
            { 25.70f, -228.53f, -79.61f },
            { 3.97f, -227.36f, -75.80f },
            { -12.90f, -230.16f, -71.50f },
            { -33.31f, -234.03f, -68.15f },
            { -51.64f, -237.55f, -68.55f },
            { -67.33f, -241.71f, -67.90f },
            { -83.18f, -247.47f, -64.94f },
            { -91.17f, -250.30f, -58.22f },
            { -108.90f, -252.29f, -56.03f },
            { -115.90f, -248.08f, -59.31f },
            { -124.04f, -245.96f, -62.38f },
            { -140.86f, -237.24f, -67.64f },
            { -158.35f, -234.20f, -70.75f },
            { -177.52f, -239.22f, -69.08f },
            { -193.20f, -252.33f, -68.39f },
            { -202.65f, -265.99f, -65.46f },
            { -213.04f, -279.34f, -66.33f },
            { -221.84f, -293.62f, -68.80f },
            { -244.49f, -299.46f, -69.14f },
            { -260.82f, -299.07f, -67.83f },
        });
}
