// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 48, boss 4831 (Lady Sarevess), 13 anchors over 161yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute48_4831()
{
    DungeonClearRouteRegistry::Register(48, DUNGEON_DIFFICULTY_NORMAL, 4831,
        {
            { -440.80f, 210.73f, -52.66f },
            { -431.47f, 228.90f, -53.17f },
            { -415.01f, 231.72f, -53.21f },
            { -399.21f, 239.92f, -57.91f },
            { -388.85f, 238.55f, -61.93f },
            { -381.84f, 242.74f, -65.59f },
            { -380.65f, 259.96f, -70.88f },
            { -380.87f, 268.34f, -73.56f },
            { -372.79f, 267.79f, -74.96f },
            { -360.66f, 284.97f, -77.57f },
            { -351.23f, 298.49f, -72.33f },
            { -347.71f, 306.64f, -68.22f },
            { -345.87f, 314.75f, -63.91f },
        });
}
