// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 129, boss 7357 (Mordresh Fire Eye), 47 anchors over 711yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute129_7357()
{
    DungeonClearRouteRegistry::Register(129, DUNGEON_DIFFICULTY_NORMAL, 7357,
        {
            { 2413.12f, 977.31f, 59.19f },
            { 2397.69f, 984.40f, 57.58f },
            { 2394.41f, 990.16f, 52.62f },
            { 2411.93f, 991.41f, 50.56f },
            { 2420.19f, 990.67f, 49.56f },
            { 2426.87f, 981.17f, 48.42f },
            { 2425.95f, 961.69f, 45.83f },
            { 2419.36f, 945.52f, 45.74f },
            { 2405.14f, 937.87f, 44.82f },
            { 2384.01f, 937.44f, 43.63f },
            { 2368.25f, 942.99f, 42.10f },
            { 2367.65f, 959.81f, 42.72f },
            { 2369.14f, 976.10f, 41.00f },
            { 2363.93f, 982.50f, 39.46f },
            { 2362.13f, 993.18f, 38.79f },
            { 2365.16f, 1001.27f, 38.47f },
            { 2371.74f, 1006.45f, 38.66f },
            { 2389.34f, 1008.33f, 38.78f },
            { 2405.91f, 1007.50f, 38.18f },
            { 2422.68f, 1011.85f, 37.82f },
            { 2431.76f, 1012.41f, 37.18f },
            { 2443.87f, 1000.91f, 38.30f },
            { 2453.70f, 980.57f, 35.66f },
            { 2463.40f, 967.17f, 37.25f },
            { 2467.01f, 957.25f, 34.33f },
            { 2462.65f, 940.95f, 29.62f },
            { 2462.50f, 932.73f, 25.35f },
            { 2466.81f, 923.69f, 25.27f },
            { 2466.94f, 902.14f, 27.72f },
            { 2461.92f, 882.56f, 30.07f },
            { 2452.20f, 869.01f, 35.68f },
            { 2451.94f, 848.53f, 40.76f },
            { 2449.58f, 836.35f, 43.88f },
            { 2445.84f, 818.54f, 43.56f },
            { 2443.66f, 802.22f, 42.46f },
            { 2442.81f, 785.13f, 43.80f },
            { 2454.99f, 770.95f, 45.01f },
            { 2467.40f, 759.30f, 46.08f },
            { 2482.65f, 747.39f, 45.78f },
            { 2500.14f, 751.96f, 41.15f },
            { 2506.71f, 757.89f, 39.52f },
            { 2516.85f, 739.80f, 40.52f },
            { 2514.13f, 722.26f, 41.55f },
            { 2506.44f, 705.56f, 47.83f },
            { 2502.78f, 697.38f, 51.44f },
            { 2485.46f, 686.88f, 53.86f },
            { 2470.43f, 678.95f, 60.27f },
        });
}
