// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 33, boss 4279 (Odo the Blindwatcher), 9 anchors over 132yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute33_4279()
{
    DungeonClearRouteRegistry::Register(33, DUNGEON_DIFFICULTY_NORMAL, 4279,
        {
            { -242.71f, 2254.93f, 101.63f },
            { -246.10f, 2233.24f, 98.28f },
            { -234.42f, 2229.26f, 93.54f },
            { -234.52f, 2218.28f, 97.75f },
            { -237.76f, 2200.02f, 97.17f },
            { -244.86f, 2178.16f, 94.96f },
            { -249.20f, 2159.25f, 92.84f },
            { -263.52f, 2147.16f, 95.01f },
            { -259.48f, 2140.18f, 99.84f },
        });
}
