// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 61961 (Jared Voss), 11 anchors over 150yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_61961()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 61961,
        {
            { -47.87f, -370.54f, 56.99f },
            { -54.15f, -376.33f, 54.34f },
            { -67.64f, -376.24f, 54.82f },
            { -67.92f, -397.43f, 55.13f },
            { -74.46f, -414.19f, 55.74f },
            { -82.28f, -431.63f, 55.54f },
            { -88.92f, -446.90f, 55.73f },
            { -92.08f, -464.01f, 56.56f },
            { -90.06f, -480.67f, 55.02f },
            { -88.62f, -488.89f, 55.25f },
            { -95.12f, -498.13f, 55.33f },
        });
}
