// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 34, boss 1696 (Targorr the Dread), 7 anchors over 89yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute34_1696()
{
    DungeonClearRouteRegistry::Register(34, DUNGEON_DIFFICULTY_NORMAL, 1696,
        {
            { 54.23f, 0.28f, -18.34f },
            { 65.67f, -0.48f, -21.69f },
            { 74.07f, -0.57f, -24.98f },
            { 93.34f, -1.61f, -25.43f },
            { 109.94f, -1.00f, -25.61f },
            { 126.72f, -0.74f, -25.05f },
            { 143.61f, 0.12f, -25.32f },
        });
}
