// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 34, boss 1717 (Hamhock), 4 anchors over 54yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute34_1717()
{
    DungeonClearRouteRegistry::Register(34, DUNGEON_DIFFICULTY_NORMAL, 1717,
        {
            { 127.55f, -48.34f, -33.31f },
            { 123.62f, -65.71f, -33.43f },
            { 116.96f, -81.07f, -33.59f },
            { 108.51f, -99.59f, -35.19f },
        });
}
