// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 33, boss 4274 (Fenrus the Devourer), 25 anchors over 358yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute33_4274()
{
    DungeonClearRouteRegistry::Register(33, DUNGEON_DIFFICULTY_NORMAL, 4274,
        {
            { -236.71f, 2146.08f, 100.03f },
            { -252.10f, 2139.12f, 100.03f },
            { -250.63f, 2118.07f, 100.06f },
            { -236.22f, 2107.03f, 98.28f },
            { -219.81f, 2102.00f, 97.47f },
            { -208.61f, 2104.75f, 97.47f },
            { -197.32f, 2124.33f, 97.50f },
            { -186.52f, 2153.28f, 97.43f },
            { -182.01f, 2170.81f, 97.55f },
            { -179.70f, 2179.70f, 97.88f },
            { -163.71f, 2172.47f, 94.44f },
            { -153.76f, 2168.31f, 94.45f },
            { -150.13f, 2174.62f, 99.88f },
            { -154.38f, 2184.61f, 104.70f },
            { -144.48f, 2182.43f, 109.28f },
            { -136.04f, 2180.25f, 112.41f },
            { -116.48f, 2172.43f, 111.10f },
            { -109.00f, 2168.14f, 107.26f },
            { -113.54f, 2159.25f, 102.50f },
            { -138.13f, 2160.98f, 105.08f },
            { -154.46f, 2167.46f, 109.09f },
            { -172.44f, 2178.40f, 111.27f },
            { -178.46f, 2184.77f, 121.56f },
            { -181.50f, 2181.82f, 125.84f },
            { -170.16f, 2179.77f, 129.80f },
        });
}
