// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3671 (Lady Anacondra), 13 anchors over 198yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3671()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3671,
        {
            { -163.49f, 132.90f, -73.66f },
            { -145.44f, 131.08f, -75.91f },
            { -137.03f, 131.82f, -77.33f },
            { -124.62f, 148.24f, -75.58f },
            { -117.25f, 163.17f, -76.86f },
            { -105.97f, 177.30f, -78.38f },
            { -93.74f, 192.01f, -80.54f },
            { -85.90f, 194.92f, -87.75f },
            { -82.71f, 202.83f, -92.73f },
            { -63.23f, 205.61f, -94.36f },
            { -57.33f, 223.33f, -92.22f },
            { -55.91f, 243.71f, -92.45f },
            { -48.32f, 264.02f, -92.24f },
        });
}
