// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 642 (Sneed's Shredder), 9 anchors over 133yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_642()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 642,
        {
            { -200.32f, -453.08f, 55.19f },
            { -191.80f, -471.66f, 54.13f },
            { -190.20f, -481.64f, 54.05f },
            { -196.25f, -497.76f, 53.35f },
            { -214.51f, -499.46f, 50.22f },
            { -231.14f, -485.80f, 49.37f },
            { -247.95f, -485.75f, 49.46f },
            { -265.23f, -485.59f, 49.41f },
            { -276.62f, -488.63f, 49.23f },
        });
}
