// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 33, boss 3887 (Baron Silverlaine), 4 anchors over 50yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute33_3887()
{
    DungeonClearRouteRegistry::Register(33, DUNGEON_DIFFICULTY_NORMAL, 3887,
        {
            { -196.72f, 2250.05f, 76.80f },
            { -216.94f, 2264.52f, 76.43f },
            { -232.22f, 2273.16f, 75.03f },
            { -239.44f, 2277.37f, 75.07f },
        });
}
