// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 33, boss 4278 (Commander Springvale), 9 anchors over 143yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute33_4278()
{
    DungeonClearRouteRegistry::Register(33, DUNGEON_DIFFICULTY_NORMAL, 4278,
        {
            { -240.35f, 2356.88f, 97.40f },
            { -248.98f, 2334.93f, 96.95f },
            { -254.34f, 2327.42f, 96.91f },
            { -272.02f, 2320.85f, 95.44f },
            { -287.34f, 2311.40f, 93.17f },
            { -291.48f, 2302.26f, 91.83f },
            { -285.51f, 2282.19f, 94.92f },
            { -264.05f, 2269.16f, 97.43f },
            { -247.65f, 2261.35f, 101.20f },
        });
}
