// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 189, boss 3974 (Houndmaster Loksey), 21 anchors over 329yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute189_3974()
{
    DungeonClearRouteRegistry::Register(189, DUNGEON_DIFFICULTY_NORMAL, 3974,
        {
            { 177.96f, -430.75f, 19.23f },
            { 194.28f, -429.02f, 18.53f },
            { 212.04f, -428.60f, 18.53f },
            { 232.53f, -426.80f, 18.53f },
            { 255.81f, -425.91f, 18.54f },
            { 263.24f, -420.35f, 18.79f },
            { 264.92f, -401.47f, 20.08f },
            { 265.26f, -383.52f, 20.08f },
            { 264.76f, -363.32f, 20.08f },
            { 264.20f, -341.12f, 19.84f },
            { 259.84f, -333.92f, 18.53f },
            { 239.01f, -328.37f, 18.53f },
            { 223.73f, -321.77f, 18.53f },
            { 220.17f, -314.04f, 18.86f },
            { 213.34f, -308.64f, 18.53f },
            { 193.61f, -304.81f, 18.53f },
            { 180.57f, -302.98f, 18.53f },
            { 169.62f, -287.12f, 19.20f },
            { 158.64f, -272.40f, 19.28f },
            { 152.26f, -263.57f, 19.20f },
            { 135.11f, -261.32f, 18.89f },
        });
}
