// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 389, boss 11517 (Oggleflint), 54 anchors over 967yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute389_11517()
{
    DungeonClearRouteRegistry::Register(389, DUNGEON_DIFFICULTY_NORMAL, 11517,
        {
            { -390.72f, 160.57f, 8.48f },
            { -368.94f, 175.87f, -21.95f },
            { -363.74f, 180.26f, -22.31f },
            { -368.46f, 178.28f, -21.22f },
            { -355.20f, 189.25f, -22.33f },
            { -335.83f, 204.48f, -20.71f },
            { -317.83f, 214.83f, -21.29f },
            { -295.72f, 214.42f, -25.49f },
            { -274.30f, 213.13f, -25.02f },
            { -251.61f, 204.06f, -22.44f },
            { -242.27f, 191.74f, -25.89f },
            { -237.08f, 172.19f, -18.60f },
            { -223.79f, 154.99f, -19.38f },
            { -205.40f, 152.01f, -23.93f },
            { -192.97f, 136.91f, -24.14f },
            { -195.84f, 115.55f, -23.15f },
            { -193.56f, 106.95f, -24.41f },
            { -199.49f, 95.48f, -24.93f },
            { -219.30f, 94.55f, -25.02f },
            { -214.31f, 94.60f, -24.56f },
            { -221.88f, 85.64f, -24.38f },
            { -206.50f, 90.55f, -25.28f },
            { -189.63f, 95.94f, -24.01f },
            { -177.75f, 81.20f, -21.49f },
            { -159.40f, 70.20f, -21.24f },
            { -141.92f, 59.46f, -22.43f },
            { -120.02f, 53.06f, -19.46f },
            { -116.65f, 30.65f, -17.91f },
            { -128.22f, 15.84f, -19.87f },
            { -149.62f, 12.90f, -22.77f },
            { -170.35f, 11.41f, -30.20f },
            { -192.62f, 9.66f, -33.57f },
            { -212.96f, 8.06f, -40.73f },
            { -238.43f, 6.05f, -45.06f },
            { -258.27f, 4.80f, -49.58f },
            { -280.78f, 2.84f, -47.24f },
            { -298.65f, -5.71f, -49.67f },
            { -298.13f, -25.43f, -59.73f },
            { -281.87f, -19.53f, -61.25f },
            { -261.84f, -9.25f, -63.86f },
            { -247.20f, -10.31f, -61.49f },
            { -272.16f, -12.39f, -63.07f },
            { -248.19f, -8.67f, -62.34f },
            { -226.93f, -7.28f, -61.62f },
            { -217.75f, -4.90f, -61.80f },
            { -218.17f, -10.59f, -61.48f },
            { -199.59f, -1.40f, -61.87f },
            { -184.53f, 3.38f, -57.36f },
            { -159.26f, 3.73f, -44.39f },
            { -148.27f, -0.31f, -38.54f },
            { -167.23f, 3.26f, -48.27f },
            { -157.93f, 4.80f, -43.44f },
            { -148.57f, 23.79f, -38.82f },
            { -148.09f, 30.83f, -38.89f },
        });
}
