// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 34, boss 1663 (Dextren Ward), 8 anchors over 129yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute34_1663()
{
    DungeonClearRouteRegistry::Register(34, DUNGEON_DIFFICULTY_NORMAL, 1663,
        {
            { 149.14f, -0.16f, -25.31f },
            { 130.91f, 7.19f, -25.61f },
            { 128.04f, 28.00f, -30.82f },
            { 134.25f, 44.08f, -33.82f },
            { 134.50f, 60.73f, -33.94f },
            { 142.25f, 84.11f, -33.86f },
            { 149.57f, 100.65f, -35.19f },
            { 154.57f, 111.89f, -34.49f },
        });
}
