// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 47, boss 4420 (Overlord Ramtusk), 14 anchors over 217yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute47_4420()
{
    DungeonClearRouteRegistry::Register(47, DUNGEON_DIFFICULTY_NORMAL, 4420,
        {
            { 2149.50f, 1418.01f, 74.76f },
            { 2151.20f, 1434.68f, 74.70f },
            { 2155.35f, 1452.56f, 74.42f },
            { 2162.20f, 1468.65f, 73.98f },
            { 2170.46f, 1486.43f, 72.92f },
            { 2173.92f, 1502.66f, 72.69f },
            { 2174.26f, 1511.04f, 69.00f },
            { 2175.32f, 1531.71f, 71.84f },
            { 2175.89f, 1553.78f, 71.61f },
            { 2181.04f, 1569.36f, 74.76f },
            { 2186.44f, 1586.68f, 79.03f },
            { 2195.28f, 1602.30f, 79.94f },
            { 2201.98f, 1618.13f, 82.62f },
            { 2202.41f, 1626.41f, 85.00f },
        });
}
