// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 33, boss 3886 (Razorclaw the Butcher), 8 anchors over 112yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute33_3886()
{
    DungeonClearRouteRegistry::Register(33, DUNGEON_DIFFICULTY_NORMAL, 3886,
        {
            { -236.78f, 2152.32f, 91.32f },
            { -234.60f, 2172.07f, 85.40f },
            { -229.57f, 2179.82f, 81.65f },
            { -214.78f, 2193.48f, 80.75f },
            { -200.69f, 2202.40f, 79.76f },
            { -189.42f, 2215.02f, 79.81f },
            { -179.47f, 2220.72f, 79.82f },
            { -182.40f, 2239.03f, 76.24f },
        });
}
