// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 48, boss 6243 (Gelihast), 51 anchors over 740yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute48_6243()
{
    DungeonClearRouteRegistry::Register(48, DUNGEON_DIFFICULTY_NORMAL, 6243,
        {
            { -345.10f, 347.47f, -53.15f },
            { -336.66f, 332.70f, -54.17f },
            { -336.99f, 316.04f, -59.37f },
            { -342.47f, 299.78f, -67.00f },
            { -348.75f, 293.97f, -71.96f },
            { -355.85f, 288.13f, -76.35f },
            { -366.77f, 275.09f, -77.53f },
            { -376.91f, 260.35f, -71.69f },
            { -393.21f, 255.36f, -66.23f },
            { -402.07f, 253.15f, -63.00f },
            { -411.81f, 250.87f, -59.21f },
            { -413.04f, 260.11f, -63.05f },
            { -420.80f, 256.83f, -59.10f },
            { -425.99f, 250.64f, -55.95f },
            { -438.55f, 239.95f, -53.25f },
            { -452.62f, 229.68f, -53.02f },
            { -459.55f, 225.12f, -53.26f },
            { -470.31f, 230.34f, -53.03f },
            { -486.23f, 219.17f, -55.71f },
            { -494.29f, 215.07f, -59.51f },
            { -514.10f, 212.89f, -62.89f },
            { -530.70f, 211.28f, -62.28f },
            { -551.23f, 211.87f, -59.68f },
            { -567.54f, 214.49f, -55.51f },
            { -578.42f, 214.06f, -49.66f },
            { -599.17f, 217.71f, -50.25f },
            { -608.37f, 218.56f, -50.67f },
            { -615.07f, 213.75f, -50.13f },
            { -612.44f, 202.45f, -49.91f },
            { -620.04f, 199.63f, -51.22f },
            { -605.81f, 182.43f, -52.97f },
            { -610.60f, 165.78f, -55.40f },
            { -616.96f, 150.10f, -55.69f },
            { -623.93f, 146.13f, -58.05f },
            { -627.54f, 129.96f, -56.86f },
            { -627.01f, 108.95f, -56.24f },
            { -624.98f, 91.33f, -55.99f },
            { -615.96f, 71.15f, -54.91f },
            { -613.25f, 60.59f, -56.56f },
            { -595.50f, 47.80f, -52.30f },
            { -586.71f, 33.83f, -50.29f },
            { -575.47f, 19.89f, -47.79f },
            { -571.48f, 8.51f, -48.22f },
            { -561.69f, 11.89f, -46.45f },
            { -545.80f, 7.38f, -42.95f },
            { -529.61f, 0.05f, -40.44f },
            { -511.27f, -1.99f, -44.14f },
            { -491.50f, -0.78f, -45.57f },
            { -476.23f, 7.09f, -48.74f },
            { -459.39f, 13.82f, -47.60f },
            { -449.71f, 17.61f, -47.53f },
        });
}
