// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 33, boss 61969 (Prelate Ironmane), 7 anchors over 94yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute33_61969()
{
    DungeonClearRouteRegistry::Register(33, DUNGEON_DIFFICULTY_NORMAL, 61969,
        {
            { -275.34f, 2297.35f, 76.15f },
            { -280.61f, 2306.71f, 85.77f },
            { -288.61f, 2309.30f, 91.36f },
            { -272.48f, 2319.04f, 95.50f },
            { -262.59f, 2316.89f, 96.02f },
            { -250.27f, 2331.94f, 96.72f },
            { -234.35f, 2353.29f, 97.52f },
        });
}
