// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 43, boss 3653 (Kresh), 5 anchors over 52yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute43_3653()
{
    DungeonClearRouteRegistry::Register(43, DUNGEON_DIFFICULTY_NORMAL, 3653,
        {
            { -0.78f, 283.85f, -88.96f },
            { -3.45f, 264.86f, -92.54f },
            { -5.73f, 248.68f, -95.59f },
            { -6.89f, 240.38f, -101.82f },
            { -6.57f, 231.99f, -104.25f },
        });
}
