// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 822, boss 63129 (Kan'za the Seer), 39 anchors over 645yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute822_63129()
{
    DungeonClearRouteRegistry::Register(822, DUNGEON_DIFFICULTY_NORMAL, 63129,
        {
            { -7547.11f, -3315.24f, 194.17f },
            { -7547.97f, -3333.23f, 193.96f },
            { -7552.47f, -3356.00f, 193.33f },
            { -7551.67f, -3379.29f, 194.48f },
            { -7547.55f, -3399.24f, 198.73f },
            { -7530.37f, -3413.82f, 199.43f },
            { -7513.25f, -3419.86f, 199.97f },
            { -7516.76f, -3443.93f, 200.12f },
            { -7531.34f, -3461.90f, 200.05f },
            { -7548.67f, -3474.78f, 200.04f },
            { -7557.08f, -3478.71f, 200.66f },
            { -7551.65f, -3475.78f, 200.69f },
            { -7564.89f, -3475.01f, 200.00f },
            { -7583.60f, -3486.54f, 200.02f },
            { -7594.77f, -3495.64f, 200.67f },
            { -7578.95f, -3488.17f, 200.67f },
            { -7604.90f, -3492.96f, 200.05f },
            { -7620.07f, -3487.47f, 200.02f },
            { -7621.89f, -3497.39f, 200.68f },
            { -7614.76f, -3481.21f, 201.01f },
            { -7612.54f, -3489.46f, 201.98f },
            { -7630.10f, -3491.75f, 200.29f },
            { -7625.06f, -3471.83f, 200.20f },
            { -7626.74f, -3455.01f, 200.02f },
            { -7630.84f, -3447.65f, 200.81f },
            { -7633.73f, -3451.33f, 200.02f },
            { -7633.71f, -3475.77f, 200.37f },
            { -7638.12f, -3492.04f, 198.51f },
            { -7655.72f, -3495.93f, 192.48f },
            { -7643.46f, -3484.30f, 193.07f },
            { -7658.21f, -3487.96f, 192.50f },
            { -7645.32f, -3487.07f, 192.40f },
            { -7664.60f, -3488.04f, 192.21f },
            { -7682.47f, -3487.74f, 192.25f },
            { -7686.47f, -3482.66f, 192.80f },
            { -7686.86f, -3495.85f, 191.11f },
            { -7719.13f, -3495.61f, 191.90f },
            { -7739.84f, -3490.22f, 192.65f },
            { -7737.80f, -3484.13f, 192.79f },
        });
}
