// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 48, boss 4829 (Aku'mai), 24 anchors over 383yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute48_4829()
{
    DungeonClearRouteRegistry::Register(48, DUNGEON_DIFFICULTY_NORMAL, 4829,
        {
            { -810.93f, -162.40f, -24.84f },
            { -814.09f, -142.28f, -25.34f },
            { -808.00f, -126.52f, -25.32f },
            { -803.96f, -119.23f, -25.02f },
            { -805.53f, -110.29f, -25.32f },
            { -813.47f, -105.93f, -25.34f },
            { -831.85f, -112.31f, -25.34f },
            { -836.94f, -128.20f, -25.34f },
            { -841.12f, -146.58f, -25.33f },
            { -844.86f, -166.94f, -25.34f },
            { -837.23f, -181.58f, -25.34f },
            { -825.86f, -193.65f, -25.34f },
            { -818.35f, -208.54f, -25.87f },
            { -822.09f, -225.16f, -25.89f },
            { -826.49f, -244.50f, -25.87f },
            { -831.72f, -261.95f, -26.37f },
            { -831.81f, -279.84f, -27.23f },
            { -828.37f, -299.54f, -30.46f },
            { -826.36f, -316.06f, -33.24f },
            { -829.78f, -332.23f, -33.36f },
            { -829.98f, -351.46f, -33.51f },
            { -829.53f, -360.64f, -33.84f },
            { -842.43f, -375.80f, -33.98f },
            { -831.08f, -392.55f, -33.60f },
        });
}
