// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 822, boss 63132 (Handler Oboka), 31 anchors over 522yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute822_63132()
{
    DungeonClearRouteRegistry::Register(822, DUNGEON_DIFFICULTY_NORMAL, 63132,
        {
            { -7524.61f, -3583.58f, 199.96f },
            { -7526.04f, -3561.69f, 199.99f },
            { -7524.18f, -3540.34f, 199.52f },
            { -7525.61f, -3554.60f, 200.52f },
            { -7526.42f, -3519.50f, 199.75f },
            { -7531.07f, -3498.32f, 200.11f },
            { -7535.09f, -3487.50f, 200.08f },
            { -7534.31f, -3491.64f, 200.81f },
            { -7531.03f, -3474.50f, 200.44f },
            { -7531.59f, -3459.71f, 200.80f },
            { -7532.68f, -3491.60f, 200.74f },
            { -7530.27f, -3472.72f, 200.02f },
            { -7520.84f, -3452.89f, 200.50f },
            { -7514.34f, -3424.84f, 200.60f },
            { -7503.34f, -3406.89f, 200.00f },
            { -7501.17f, -3397.77f, 200.55f },
            { -7504.57f, -3400.02f, 200.49f },
            { -7503.32f, -3404.96f, 200.53f },
            { -7516.83f, -3412.79f, 199.32f },
            { -7537.42f, -3406.34f, 198.50f },
            { -7522.38f, -3405.87f, 199.43f },
            { -7519.49f, -3409.93f, 199.49f },
            { -7542.26f, -3402.83f, 198.62f },
            { -7551.83f, -3384.18f, 195.43f },
            { -7552.78f, -3362.59f, 193.88f },
            { -7535.56f, -3371.80f, 192.91f },
            { -7542.17f, -3369.32f, 193.50f },
            { -7549.97f, -3350.55f, 193.46f },
            { -7554.05f, -3342.82f, 193.95f },
            { -7550.11f, -3313.98f, 193.31f },
            { -7560.11f, -3315.52f, 193.93f },
        });
}
