// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 109, boss 5715 (Hukku), 35 anchors over 515yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute109_5715()
{
    DungeonClearRouteRegistry::Register(109, DUNGEON_DIFFICULTY_NORMAL, 5715,
        {
            { -534.50f, 140.93f, -65.09f },
            { -533.33f, 149.30f, -67.84f },
            { -547.21f, 163.55f, -69.40f },
            { -563.25f, 166.85f, -69.40f },
            { -568.36f, 173.53f, -69.40f },
            { -564.20f, 182.92f, -69.25f },
            { -551.63f, 181.55f, -61.91f },
            { -543.54f, 179.28f, -56.06f },
            { -535.20f, 172.41f, -53.59f },
            { -541.63f, 153.43f, -54.03f },
            { -548.00f, 137.69f, -53.95f },
            { -554.10f, 121.95f, -53.95f },
            { -561.77f, 103.13f, -53.95f },
            { -568.37f, 85.27f, -53.95f },
            { -575.44f, 75.58f, -54.10f },
            { -566.85f, 74.96f, -53.95f },
            { -555.91f, 62.59f, -53.77f },
            { -545.01f, 46.95f, -53.95f },
            { -531.26f, 32.62f, -53.95f },
            { -516.02f, 18.00f, -53.95f },
            { -496.42f, 9.58f, -53.49f },
            { -478.54f, 4.88f, -53.95f },
            { -457.00f, 3.76f, -53.95f },
            { -437.82f, 6.65f, -53.95f },
            { -421.05f, 8.91f, -53.95f },
            { -402.88f, 11.59f, -53.94f },
            { -386.34f, 9.95f, -58.24f },
            { -376.40f, 4.56f, -64.74f },
            { -366.98f, 9.70f, -69.39f },
            { -364.71f, 17.75f, -69.39f },
            { -371.90f, 25.36f, -69.39f },
            { -390.42f, 29.14f, -69.39f },
            { -401.14f, 46.48f, -65.62f },
            { -404.78f, 53.97f, -66.34f },
            { -413.37f, 53.70f, -65.35f },
        });
}
