// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 47, boss 62503 (Rotthorn), 36 anchors over 516yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute47_62503()
{
    DungeonClearRouteRegistry::Register(47, DUNGEON_DIFFICULTY_NORMAL, 62503,
        {
            { 2202.75f, 1632.77f, 85.71f },
            { 2200.36f, 1614.85f, 81.58f },
            { 2183.23f, 1625.22f, 81.19f },
            { 2167.78f, 1631.14f, 81.63f },
            { 2159.58f, 1632.10f, 81.77f },
            { 2151.16f, 1627.19f, 82.44f },
            { 2140.78f, 1640.38f, 81.91f },
            { 2130.73f, 1657.51f, 82.09f },
            { 2126.35f, 1674.29f, 82.43f },
            { 2121.37f, 1691.51f, 80.55f },
            { 2114.29f, 1711.11f, 80.97f },
            { 2102.48f, 1727.29f, 78.16f },
            { 2091.54f, 1739.56f, 77.43f },
            { 2072.68f, 1734.65f, 76.58f },
            { 2055.29f, 1724.64f, 76.74f },
            { 2040.07f, 1713.29f, 73.51f },
            { 2028.39f, 1701.49f, 70.90f },
            { 2016.37f, 1684.65f, 66.52f },
            { 2004.89f, 1681.94f, 65.44f },
            { 1989.56f, 1691.00f, 60.37f },
            { 1983.19f, 1696.41f, 59.78f },
            { 1984.42f, 1715.35f, 59.35f },
            { 1983.90f, 1732.21f, 59.66f },
            { 1982.77f, 1749.59f, 58.59f },
            { 1986.79f, 1767.74f, 55.64f },
            { 1987.65f, 1776.00f, 55.51f },
            { 1983.64f, 1776.42f, 59.82f },
            { 1980.13f, 1769.34f, 64.31f },
            { 1972.02f, 1770.08f, 68.06f },
            { 1965.52f, 1776.58f, 70.23f },
            { 1962.83f, 1785.91f, 70.21f },
            { 1965.30f, 1793.76f, 71.25f },
            { 1983.55f, 1801.11f, 76.40f },
            { 1991.79f, 1802.27f, 77.89f },
            { 1996.11f, 1818.89f, 81.00f },
            { 1989.11f, 1823.45f, 83.08f },
        });
}
