// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 230, boss 9024 (Pyromancer Loregrain), 46 anchors over 691yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute230_9024()
{
    DungeonClearRouteRegistry::Register(230, DUNGEON_DIFFICULTY_NORMAL, 9024,
        {
            { 889.68f, -262.06f, -71.32f },
            { 891.33f, -272.39f, -71.32f },
            { 903.33f, -284.14f, -71.32f },
            { 915.26f, -296.21f, -71.53f },
            { 927.22f, -308.27f, -71.76f },
            { 940.28f, -321.21f, -71.22f },
            { 951.62f, -334.94f, -71.21f },
            { 962.50f, -349.48f, -71.74f },
            { 972.83f, -362.76f, -67.05f },
            { 981.44f, -362.64f, -65.57f },
            { 968.89f, -378.30f, -61.10f },
            { 958.86f, -395.35f, -60.26f },
            { 949.08f, -397.18f, -57.94f },
            { 943.10f, -402.70f, -55.50f },
            { 935.02f, -404.02f, -52.12f },
            { 921.61f, -390.58f, -48.75f },
            { 909.42f, -378.22f, -48.98f },
            { 903.80f, -372.04f, -49.40f },
            { 900.11f, -354.44f, -49.48f },
            { 897.74f, -337.08f, -49.29f },
            { 900.57f, -320.42f, -49.41f },
            { 897.31f, -311.70f, -49.37f },
            { 890.95f, -317.54f, -49.46f },
            { 873.98f, -311.09f, -49.60f },
            { 865.78f, -304.61f, -49.95f },
            { 867.48f, -294.01f, -49.38f },
            { 855.73f, -278.74f, -49.94f },
            { 850.47f, -256.70f, -49.42f },
            { 846.70f, -249.14f, -49.03f },
            { 830.45f, -250.47f, -48.82f },
            { 817.79f, -262.68f, -48.76f },
            { 806.31f, -277.44f, -42.87f },
            { 788.73f, -279.38f, -42.77f },
            { 770.86f, -278.65f, -42.39f },
            { 751.88f, -278.06f, -42.32f },
            { 735.16f, -276.00f, -42.29f },
            { 726.91f, -276.15f, -42.31f },
            { 719.85f, -272.33f, -42.32f },
            { 703.27f, -276.90f, -42.73f },
            { 685.60f, -277.32f, -42.62f },
            { 667.19f, -279.62f, -42.89f },
            { 649.24f, -281.17f, -42.65f },
            { 632.42f, -279.94f, -42.63f },
            { 612.32f, -278.16f, -42.86f },
            { 600.41f, -274.65f, -82.52f },
            { 583.42f, -266.83f, -78.53f },
        });
}
