// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 47, boss 4421 (Charlga Razorflank), 18 anchors over 247yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute47_4421()
{
    DungeonClearRouteRegistry::Register(47, DUNGEON_DIFFICULTY_NORMAL, 4421,
        {
            { 2044.49f, 2017.36f, 60.24f },
            { 2060.56f, 2014.15f, 63.50f },
            { 2074.94f, 2005.79f, 62.34f },
            { 2089.40f, 1997.38f, 63.73f },
            { 2105.34f, 1987.35f, 64.94f },
            { 2124.69f, 1984.14f, 63.29f },
            { 2133.49f, 1981.43f, 60.94f },
            { 2142.21f, 1983.76f, 60.27f },
            { 2156.99f, 1971.74f, 62.20f },
            { 2167.50f, 1957.41f, 57.80f },
            { 2171.37f, 1949.54f, 59.57f },
            { 2163.84f, 1943.10f, 62.83f },
            { 2166.07f, 1926.41f, 66.34f },
            { 2166.67f, 1918.25f, 68.38f },
            { 2179.24f, 1906.83f, 70.21f },
            { 2187.68f, 1892.14f, 72.15f },
            { 2192.07f, 1884.62f, 72.75f },
            { 2191.63f, 1867.05f, 79.26f },
        });
}
