// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 647 (Captain Greenskin), 9 anchors over 93yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_647()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 647,
        {
            { -7.88f, -776.79f, 9.29f },
            { -11.02f, -786.49f, 13.35f },
            { -19.89f, -792.75f, 18.07f },
            { -27.97f, -795.33f, 18.76f },
            { -46.76f, -787.43f, 18.43f },
            { -55.13f, -786.72f, 18.18f },
            { -50.51f, -795.08f, 38.81f },
            { -49.30f, -804.15f, 42.68f },
            { -59.13f, -817.82f, 42.24f },
        });
}
