// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 189, boss 4543 (Bloodmage Thalnos), 38 anchors over 502yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute189_4543()
{
    DungeonClearRouteRegistry::Register(189, DUNGEON_DIFFICULTY_NORMAL, 4543,
        {
            { 1688.99f, 1053.48f, 18.68f },
            { 1698.62f, 1054.86f, 18.49f },
            { 1703.16f, 1074.17f, 15.23f },
            { 1704.18f, 1082.42f, 11.11f },
            { 1704.80f, 1090.88f, 7.51f },
            { 1725.47f, 1094.17f, 6.82f },
            { 1733.79f, 1093.50f, 6.82f },
            { 1742.60f, 1100.28f, 6.82f },
            { 1760.94f, 1103.49f, 7.54f },
            { 1760.52f, 1123.54f, 7.49f },
            { 1765.98f, 1141.02f, 7.49f },
            { 1781.87f, 1157.12f, 7.49f },
            { 1791.96f, 1171.74f, 6.82f },
            { 1796.73f, 1179.24f, 8.90f },
            { 1796.90f, 1188.12f, 13.34f },
            { 1797.07f, 1196.58f, 17.66f },
            { 1797.65f, 1214.69f, 18.16f },
            { 1797.74f, 1231.62f, 18.24f },
            { 1798.06f, 1248.33f, 18.33f },
            { 1798.40f, 1266.03f, 18.43f },
            { 1798.81f, 1287.46f, 18.55f },
            { 1799.13f, 1303.93f, 18.65f },
            { 1799.47f, 1321.45f, 21.10f },
            { 1797.34f, 1329.67f, 18.92f },
            { 1799.48f, 1346.58f, 18.89f },
            { 1799.47f, 1362.09f, 18.89f },
            { 1799.12f, 1379.26f, 18.86f },
            { 1797.96f, 1397.01f, 23.49f },
            { 1799.47f, 1408.46f, 18.58f },
            { 1800.33f, 1416.78f, 14.19f },
            { 1809.65f, 1418.92f, 9.04f },
            { 1811.00f, 1427.16f, 8.55f },
            { 1803.67f, 1431.81f, 8.05f },
            { 1795.52f, 1431.08f, 3.48f },
            { 1787.21f, 1426.00f, -0.41f },
            { 1793.73f, 1418.42f, -3.57f },
            { 1801.90f, 1417.89f, -6.68f },
            { 1810.32f, 1416.92f, -8.56f },
        });
}
