// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 646 (Mr. Smite), 28 anchors over 433yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_646()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 646,
        {
            { -109.34f, -569.70f, 51.89f },
            { -127.75f, -569.36f, 51.32f },
            { -146.68f, -563.65f, 51.30f },
            { -162.82f, -557.12f, 51.45f },
            { -177.66f, -544.16f, 51.35f },
            { -183.05f, -537.68f, 51.34f },
            { -201.41f, -540.51f, 51.26f },
            { -202.20f, -548.59f, 51.26f },
            { -189.97f, -567.13f, 50.70f },
            { -181.93f, -581.60f, 20.15f },
            { -164.90f, -582.51f, 19.35f },
            { -148.01f, -584.47f, 18.88f },
            { -138.95f, -587.56f, 18.21f },
            { -130.69f, -609.19f, 14.75f },
            { -124.83f, -625.57f, 13.57f },
            { -117.34f, -641.05f, 11.06f },
            { -107.07f, -659.11f, 7.94f },
            { -98.20f, -676.14f, 7.99f },
            { -83.39f, -688.51f, 2.73f },
            { -78.33f, -695.42f, -1.65f },
            { -72.93f, -703.59f, -7.11f },
            { -67.34f, -712.34f, -10.47f },
            { -57.19f, -728.37f, -9.36f },
            { -48.38f, -742.42f, -10.98f },
            { -37.15f, -760.09f, -12.28f },
            { -21.93f, -774.32f, -5.88f },
            { -13.67f, -776.59f, 2.02f },
            { -8.70f, -783.79f, 12.63f },
        });
}
