// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 61963 (Masterpiece Harvester), 47 anchors over 777yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_61963()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 61963,
        {
            { -99.35f, -513.70f, 54.75f },
            { -92.13f, -509.90f, 56.10f },
            { -90.58f, -494.08f, 54.38f },
            { -90.84f, -478.86f, 54.72f },
            { -91.96f, -458.49f, 55.93f },
            { -85.28f, -437.38f, 55.87f },
            { -78.23f, -422.02f, 55.20f },
            { -71.24f, -405.71f, 55.04f },
            { -68.55f, -386.97f, 55.29f },
            { -84.65f, -379.29f, 57.01f },
            { -103.12f, -382.60f, 57.57f },
            { -118.20f, -388.71f, 57.16f },
            { -136.12f, -397.50f, 59.79f },
            { -155.34f, -402.16f, 56.79f },
            { -170.55f, -408.18f, 57.24f },
            { -179.27f, -426.19f, 54.93f },
            { -184.13f, -442.16f, 54.32f },
            { -190.69f, -457.37f, 54.51f },
            { -190.65f, -474.82f, 54.04f },
            { -193.47f, -492.58f, 53.52f },
            { -197.39f, -500.75f, 53.22f },
            { -216.39f, -494.37f, 49.06f },
            { -233.09f, -489.78f, 49.02f },
            { -250.36f, -487.23f, 49.45f },
            { -267.23f, -485.59f, 49.34f },
            { -279.15f, -499.66f, 49.49f },
            { -282.47f, -521.19f, 48.69f },
            { -289.03f, -536.82f, 49.44f },
            { -288.45f, -553.41f, 49.45f },
            { -289.71f, -571.13f, 49.06f },
            { -297.83f, -589.68f, 48.50f },
            { -290.77f, -593.59f, 49.26f },
            { -275.96f, -586.53f, 50.33f },
            { -261.14f, -578.74f, 50.53f },
            { -244.45f, -575.38f, 51.14f },
            { -228.34f, -571.41f, 51.23f },
            { -215.16f, -560.92f, 51.23f },
            { -207.55f, -557.16f, 51.23f },
            { -198.88f, -536.30f, 51.23f },
            { -191.86f, -532.20f, 51.23f },
            { -171.46f, -544.51f, 51.23f },
            { -158.50f, -555.56f, 51.23f },
            { -153.71f, -566.38f, 52.31f },
            { -134.65f, -566.35f, 51.23f },
            { -118.25f, -578.31f, 51.23f },
            { -99.71f, -574.18f, 52.99f },
            { -91.45f, -579.00f, 51.85f },
        });
}
