// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 822, boss 63131 (Battlemaster Ubukaz), 43 anchors over 701yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute822_63131()
{
    DungeonClearRouteRegistry::Register(822, DUNGEON_DIFFICULTY_NORMAL, 63131,
        {
            { -7737.80f, -3484.13f, 192.79f },
            { -7730.51f, -3493.06f, 193.21f },
            { -7705.82f, -3496.49f, 192.55f },
            { -7692.14f, -3510.38f, 192.34f },
            { -7712.59f, -3496.14f, 191.83f },
            { -7717.96f, -3495.95f, 191.81f },
            { -7695.17f, -3498.60f, 192.29f },
            { -7674.10f, -3508.58f, 191.31f },
            { -7653.82f, -3510.17f, 192.05f },
            { -7681.11f, -3504.72f, 191.25f },
            { -7651.96f, -3509.79f, 192.05f },
            { -7635.93f, -3510.50f, 199.04f },
            { -7630.60f, -3522.90f, 200.11f },
            { -7614.59f, -3531.05f, 200.91f },
            { -7632.98f, -3538.34f, 200.62f },
            { -7617.67f, -3532.04f, 201.25f },
            { -7623.88f, -3526.32f, 200.02f },
            { -7627.64f, -3548.00f, 204.48f },
            { -7640.69f, -3563.85f, 210.20f },
            { -7654.84f, -3577.64f, 215.02f },
            { -7646.23f, -3594.11f, 214.90f },
            { -7642.80f, -3603.30f, 214.85f },
            { -7636.89f, -3594.98f, 214.90f },
            { -7644.62f, -3590.74f, 215.51f },
            { -7630.59f, -3594.12f, 215.74f },
            { -7641.57f, -3592.15f, 215.58f },
            { -7623.03f, -3580.73f, 215.06f },
            { -7630.83f, -3598.80f, 214.87f },
            { -7619.99f, -3615.29f, 215.10f },
            { -7615.19f, -3625.68f, 215.85f },
            { -7621.16f, -3624.63f, 215.98f },
            { -7621.29f, -3632.10f, 215.65f },
            { -7610.40f, -3638.53f, 215.39f },
            { -7618.24f, -3624.63f, 215.91f },
            { -7633.28f, -3643.93f, 215.46f },
            { -7666.04f, -3655.99f, 216.07f },
            { -7672.50f, -3657.11f, 216.63f },
            { -7657.53f, -3651.94f, 216.58f },
            { -7670.18f, -3657.84f, 216.08f },
            { -7686.58f, -3670.28f, 216.06f },
            { -7689.44f, -3673.74f, 216.06f },
            { -7708.36f, -3680.08f, 218.20f },
            { -7702.75f, -3686.54f, 218.95f },
        });
}
