// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 230, boss 9017 (Lord Incendius), 32 anchors over 537yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute230_9017()
{
    DungeonClearRouteRegistry::Register(230, DUNGEON_DIFFICULTY_NORMAL, 9017,
        {
            { 456.93f, 34.09f, -68.09f },
            { 471.46f, 25.54f, -68.88f },
            { 487.36f, 19.41f, -69.82f },
            { 504.27f, 14.99f, -69.90f },
            { 519.41f, 21.92f, -70.89f },
            { 524.42f, 15.13f, -70.91f },
            { 542.52f, 13.89f, -69.69f },
            { 560.46f, 13.23f, -69.87f },
            { 578.23f, 14.65f, -69.71f },
            { 597.64f, 11.61f, -72.13f },
            { 612.87f, 1.76f, -73.85f },
            { 620.07f, -2.96f, -73.24f },
            { 627.18f, -18.48f, -73.24f },
            { 642.76f, -27.12f, -72.72f },
            { 653.41f, -40.09f, -72.73f },
            { 665.20f, -52.03f, -72.50f },
            { 675.30f, -65.92f, -72.02f },
            { 691.65f, -76.62f, -71.55f },
            { 705.16f, -86.66f, -70.76f },
            { 716.55f, -99.85f, -71.12f },
            { 728.04f, -112.42f, -71.22f },
            { 740.79f, -123.85f, -71.61f },
            { 754.04f, -134.37f, -72.11f },
            { 767.14f, -146.70f, -73.16f },
            { 780.85f, -158.98f, -72.74f },
            { 791.80f, -173.15f, -73.18f },
            { 806.75f, -187.34f, -73.16f },
            { 818.45f, -201.70f, -72.13f },
            { 831.19f, -212.69f, -71.75f },
            { 845.74f, -222.80f, -71.36f },
            { 859.84f, -234.07f, -71.23f },
            { 875.76f, -252.42f, -71.71f },
        });
}
