// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 47, boss 4424 (Aggem Thorncurse), 42 anchors over 667yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute47_4424()
{
    DungeonClearRouteRegistry::Register(47, DUNGEON_DIFFICULTY_NORMAL, 4424,
        {
            { 2142.14f, 1581.26f, 81.23f },
            { 2125.56f, 1570.24f, 80.58f },
            { 2110.77f, 1558.77f, 81.25f },
            { 2100.45f, 1551.97f, 81.60f },
            { 2090.03f, 1564.61f, 83.11f },
            { 2078.60f, 1577.70f, 82.91f },
            { 2070.08f, 1592.59f, 78.25f },
            { 2059.46f, 1605.56f, 77.58f },
            { 2049.19f, 1619.97f, 80.99f },
            { 2048.17f, 1638.97f, 83.85f },
            { 2044.77f, 1646.49f, 82.16f },
            { 2029.22f, 1653.92f, 81.43f },
            { 2011.78f, 1645.27f, 80.38f },
            { 2005.16f, 1639.89f, 80.44f },
            { 1997.42f, 1622.35f, 81.96f },
            { 1995.72f, 1614.27f, 83.54f },
            { 2000.68f, 1596.51f, 80.47f },
            { 2006.72f, 1577.55f, 81.68f },
            { 2013.92f, 1556.80f, 81.78f },
            { 2018.79f, 1539.50f, 80.81f },
            { 2025.65f, 1517.88f, 79.04f },
            { 2029.10f, 1500.65f, 73.72f },
            { 2029.86f, 1492.46f, 71.03f },
            { 2041.14f, 1478.21f, 68.09f },
            { 2053.75f, 1467.81f, 67.33f },
            { 2066.84f, 1456.18f, 67.37f },
            { 2085.05f, 1441.99f, 67.80f },
            { 2101.17f, 1440.68f, 64.64f },
            { 2119.23f, 1444.36f, 65.13f },
            { 2129.38f, 1459.05f, 66.29f },
            { 2147.33f, 1475.38f, 67.80f },
            { 2154.48f, 1493.28f, 68.46f },
            { 2162.25f, 1495.55f, 70.25f },
            { 2166.76f, 1503.43f, 71.46f },
            { 2175.58f, 1508.07f, 71.32f },
            { 2167.97f, 1513.66f, 67.90f },
            { 2162.08f, 1519.14f, 71.94f },
            { 2143.17f, 1511.39f, 72.60f },
            { 2139.50f, 1503.03f, 72.79f },
            { 2123.90f, 1487.24f, 73.07f },
            { 2111.42f, 1471.55f, 73.33f },
            { 2100.68f, 1458.54f, 73.44f },
        });
}
