// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 47, boss 4428 (Death Speaker Jargba), 14 anchors over 196yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute47_4428()
{
    DungeonClearRouteRegistry::Register(47, DUNGEON_DIFFICULTY_NORMAL, 4428,
        {
            { 2099.88f, 1452.52f, 74.52f },
            { 2110.65f, 1470.09f, 73.24f },
            { 2122.34f, 1484.83f, 73.06f },
            { 2133.25f, 1498.60f, 73.01f },
            { 2144.12f, 1511.49f, 72.65f },
            { 2160.90f, 1516.56f, 72.07f },
            { 2167.53f, 1514.10f, 67.84f },
            { 2171.80f, 1504.97f, 72.08f },
            { 2173.09f, 1495.08f, 72.91f },
            { 2167.13f, 1479.25f, 72.96f },
            { 2160.27f, 1463.06f, 74.10f },
            { 2152.96f, 1447.48f, 75.33f },
            { 2148.74f, 1430.84f, 75.13f },
            { 2147.65f, 1421.56f, 74.23f },
        });
}
