// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 389, boss 11519 (Bazzalan), 16 anchors over 224yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute389_11519()
{
    DungeonClearRouteRegistry::Register(389, DUNGEON_DIFFICULTY_NORMAL, 11519,
        {
            { -359.65f, 211.47f, -21.19f },
            { -337.73f, 230.86f, -16.10f },
            { -324.51f, 244.02f, -10.59f },
            { -337.63f, 253.21f, -9.07f },
            { -355.93f, 253.91f, -6.07f },
            { -369.64f, 256.68f, -4.60f },
            { -377.68f, 252.77f, -4.28f },
            { -379.28f, 246.10f, -4.15f },
            { -377.47f, 250.57f, -4.14f },
            { -382.55f, 242.80f, -4.23f },
            { -378.19f, 232.00f, -1.17f },
            { -393.35f, 220.48f, -1.11f },
            { -400.02f, 216.58f, -1.10f },
            { -404.75f, 184.72f, 6.09f },
            { -396.18f, 166.34f, 7.74f },
            { -390.85f, 160.90f, 8.48f },
        });
}
