// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 429, boss 14327 (Lethtendris), 52 anchors over 668yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute429_14327()
{
    DungeonClearRouteRegistry::Register(429, DUNGEON_DIFFICULTY_NORMAL, 14327,
        {
            { -25.98f, -448.24f, -36.09f },
            { -15.68f, -467.17f, -37.67f },
            { -6.55f, -471.64f, -37.96f },
            { -1.63f, -478.10f, -36.41f },
            { -0.50f, -486.45f, -36.41f },
            { 8.38f, -492.31f, -36.41f },
            { 25.16f, -492.74f, -36.41f },
            { 41.80f, -492.44f, -38.21f },
            { 63.14f, -492.58f, -40.99f },
            { 80.22f, -492.54f, -43.29f },
            { 97.41f, -490.10f, -45.79f },
            { 105.02f, -486.73f, -47.68f },
            { 111.91f, -472.11f, -50.83f },
            { 110.22f, -464.01f, -52.27f },
            { 102.62f, -454.79f, -54.67f },
            { 85.85f, -450.92f, -57.19f },
            { 63.55f, -450.67f, -58.59f },
            { 45.37f, -449.90f, -58.61f },
            { 28.04f, -449.10f, -58.63f },
            { 11.47f, -448.62f, -58.63f },
            { -8.10f, -447.50f, -58.62f },
            { -25.43f, -447.21f, -58.62f },
            { -48.35f, -447.90f, -58.61f },
            { -64.97f, -447.71f, -58.61f },
            { -82.87f, -447.79f, -58.61f },
            { -100.08f, -447.87f, -58.61f },
            { -118.95f, -447.96f, -58.54f },
            { -129.06f, -448.00f, -56.99f },
            { -133.99f, -454.66f, -53.74f },
            { -138.72f, -461.68f, -49.21f },
            { -142.51f, -469.57f, -44.39f },
            { -143.75f, -477.82f, -40.45f },
            { -141.71f, -487.05f, -36.10f },
            { -136.92f, -494.00f, -32.17f },
            { -128.64f, -499.49f, -27.47f },
            { -120.72f, -501.30f, -23.58f },
            { -112.39f, -501.02f, -19.74f },
            { -104.96f, -497.34f, -15.84f },
            { -98.85f, -492.04f, -12.12f },
            { -93.64f, -485.66f, -8.49f },
            { -90.46f, -477.44f, -4.62f },
            { -98.15f, -462.27f, -4.22f },
            { -102.25f, -454.46f, -4.23f },
            { -94.14f, -452.92f, -1.18f },
            { -84.36f, -452.06f, 3.17f },
            { -76.07f, -451.25f, 6.85f },
            { -66.48f, -450.88f, 11.11f },
            { -57.92f, -451.18f, 14.91f },
            { -41.46f, -447.86f, 16.40f },
            { -24.59f, -445.98f, 16.41f },
            { -16.33f, -444.98f, 16.41f },
            { -5.79f, -461.03f, 16.98f },
        });
}
