-- ==============================================
-- FILE: character_inventory_copy.sql
-- GENERATED: 20260812142512
-- ==============================================
-- ObjectMgr::BackupCharacterInventory() runs TRUNCATE on
-- `character_inventory_copy` and refills it from `character_inventory`, but
-- nothing ever creates that table - there is no CREATE for it anywhere under
-- sql/.
--
-- The call does not sit in the startup path. It comes from
-- HonorMaintenancer::DoMaintenance(), so it only fires once honor maintenance
-- falls due. A server therefore runs fine for days and then dies one morning
-- with
--
--     SQL: TRUNCATE `character_inventory_copy`
--     [1146] Table '<db>.character_inventory_copy' doesn't exist
--     Your database structure is not up to date.
--
-- and does not come back: the maintenance is still due after the automatic
-- restart, so every attempt fails at the same point. What looks like a random
-- crash is a restart loop.
--
-- Two things make this easy to walk into. The failure message names the
-- sql/updates folders rather than the missing table, and
-- mangosd.conf.dist.in ships `BackupCharacterInventory = 1` while the code
-- itself defaults the setting to false - so taking the shipped config as-is
-- turns on a feature whose table nobody creates.
--
-- LIKE is deliberate: it keeps the copy in step with the original, which is
-- what the INSERT ... SELECT * in BackupCharacterInventory() needs. Servers
-- that already have the table are untouched.

CREATE TABLE IF NOT EXISTS `character_inventory_copy` LIKE `character_inventory`;
